services:
  - type: web
    name: jsonspark-backend
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    env: node
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production